import { Inter } from "next/font/google";
import { Theme } from '@radix-ui/themes';
import { Navbar } from '@/components/Navbar';

import '@radix-ui/themes/styles.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-background-color">
        <Navbar />
        <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%">
        <main className="pt-20 h-screen  flex flex-col items-center justify-between bg-background-color overflow-y-scroll no-scrollbar">
          {children}
          </main>
        </Theme>
      </body>
    </html>
  );
}
